var manifest = [
	{src : "assets/images/play.png", 		type : createjs.LoadQueue.IMAGE, id : "playbutton"},
      {src : "assets/images/settings.png",      type : createjs.LoadQueue.IMAGE, id : "settingsbutton"},
      {src : "assets/images/trophy.png",        type : createjs.LoadQueue.IMAGE, id : "trophy"},
	{src : "assets/images/logonoas.png", 	type : createjs.LoadQueue.IMAGE, id : "logonoas"},
	{src : "assets/images/noas.png", 		type : createjs.LoadQueue.IMAGE, id : "noas"},
	{src : "assets/images/indicacao.png", 	type : createjs.LoadQueue.IMAGE, id : "indicacao"},
	{src : "assets/images/titulo.png", 		type : createjs.LoadQueue.IMAGE, id : "titulo"},
	{src : "assets/images/concentracao.png",  type : createjs.LoadQueue.IMAGE, id : "concentracao"},
	{src : "assets/images/confirm.png",		type : createjs.LoadQueue.IMAGE, id : "confirmbutton"},
      {src : "assets/images/opcoesbackground.png",type : createjs.LoadQueue.IMAGE, id : "opcoesbackground"},
      {src : "assets/images/simplebackground.png",type : createjs.LoadQueue.IMAGE, id : "simplebackground"},
      {src : "assets/images/background.png",    type : createjs.LoadQueue.IMAGE, id : "background"},
      {src : "assets/images/cleanbutton.png",   type : createjs.LoadQueue.IMAGE, id : "cleanbutton"},
      // opções do menu
      {src : "assets/images/home.png",            type : createjs.LoadQueue.IMAGE, id : "home"},
      {src : "assets/images/info.png",            type : createjs.LoadQueue.IMAGE, id : "info"},
      {src : "assets/images/midiaon.png",         type : createjs.LoadQueue.IMAGE, id : "midiaon"},
      {src : "assets/images/midiaoff.png",        type : createjs.LoadQueue.IMAGE, id : "midiaoff"},
      {src : "assets/images/fullscreenon.png",    type : createjs.LoadQueue.IMAGE, id : "fullscreenon"},
      {src : "assets/images/fullscreenoff.png",   type : createjs.LoadQueue.IMAGE, id : "fullscreenoff"},
      // informacoes
      {src : "assets/images/credits.png",                 type : createjs.LoadQueue.IMAGE, id : "credits"},
      {src : "assets/images/informacoesbackground.png",   type : createjs.LoadQueue.IMAGE, id : "informacoesbackground"},
      // créditos
      {src : "assets/images/creditosbackground.png",   type : createjs.LoadQueue.IMAGE, id : "creditosbackground"},
      // finalizacao
      {src : "assets/images/novojogo.png", type : createjs.LoadQueue.IMAGE, id : "novojogobutton"},
      {src : "assets/images/ranking.png",  type : createjs.LoadQueue.IMAGE, id : "rankingbutton"},
      // ranking
      {src : "assets/images/rankingbackground.png",   type : createjs.LoadQueue.IMAGE, id : "rankingbackground"},
      // ajuda
      {src : "assets/images/helpimage.png",   type : createjs.LoadQueue.IMAGE, id : "helpimage"},
      {src : "assets/images/helpbutton.png",  type : createjs.LoadQueue.IMAGE, id : "helpbutton"},
      {src : "assets/images/pecashelp.png",   type : createjs.LoadQueue.IMAGE, id : "pecashelp"},
      // images da cruzadinha 
      // level 1
      {src : "assets/word/morangos.png",    type : createjs.LoadQueue.IMAGE, id : "morangos"},
      {src : "assets/word/dados.png",       type : createjs.LoadQueue.IMAGE, id : "dados"},
      {src : "assets/word/tesoura.png",     type : createjs.LoadQueue.IMAGE, id : "tesoura"},
      // level 2
      {src : "assets/word/cadeado.png",     type : createjs.LoadQueue.IMAGE, id : "cadeado"},
      {src : "assets/word/bananas.png",     type : createjs.LoadQueue.IMAGE, id : "bananas"},
      {src : "assets/word/borboleta.png",   type : createjs.LoadQueue.IMAGE, id : "borboleta"},
      {src : "assets/word/gato.png",        type : createjs.LoadQueue.IMAGE, id : "gato"},
      {src : "assets/word/mala.png",        type : createjs.LoadQueue.IMAGE, id : "mala"},
      // level 3
      {src : "assets/word/cenouras.png",    type : createjs.LoadQueue.IMAGE, id : "cenouras"},
      {src : "assets/word/sorvete.png",     type : createjs.LoadQueue.IMAGE, id : "sorvete"},
      {src : "assets/word/casa.png",        type : createjs.LoadQueue.IMAGE, id : "casa"},
      {src : "assets/word/carro.png",       type : createjs.LoadQueue.IMAGE, id : "carro"},
      {src : "assets/word/bola.png",        type : createjs.LoadQueue.IMAGE, id : "bola"},
      {src : "assets/word/bota.png",        type : createjs.LoadQueue.IMAGE, id : "bota"},
      // level 4
      {src : "assets/word/telefone.png",    type : createjs.LoadQueue.IMAGE, id : "telefone"},
      {src : "assets/word/sino.png",        type : createjs.LoadQueue.IMAGE, id : "sino"},
      {src : "assets/word/caju.png",        type : createjs.LoadQueue.IMAGE, id : "caju"},
      {src : "assets/word/flor.png",        type : createjs.LoadQueue.IMAGE, id : "flor"},
      {src : "assets/word/velas.png",       type : createjs.LoadQueue.IMAGE, id : "velas"},
      {src : "assets/word/torta.png",       type : createjs.LoadQueue.IMAGE, id : "torta"},
      {src : "assets/word/porta.png",       type : createjs.LoadQueue.IMAGE, id : "porta"},
      {src : "assets/word/uvas.png",        type : createjs.LoadQueue.IMAGE, id : "uvas"},
      {src : "assets/word/chaves.png",      type : createjs.LoadQueue.IMAGE, id : "chaves"},
      // level 5
      {src : "assets/word/lapis.png",       type : createjs.LoadQueue.IMAGE, id : "lapis"},
      {src : "assets/word/lampada.png",     type : createjs.LoadQueue.IMAGE, id : "lampada"},
      {src : "assets/word/celular.png",     type : createjs.LoadQueue.IMAGE, id : "celular"},
      {src : "assets/word/sapatos.png",     type : createjs.LoadQueue.IMAGE, id : "sapatos"},
      {src : "assets/word/relogio.png",     type : createjs.LoadQueue.IMAGE, id : "relogio"},
      {src : "assets/word/ventilador.png",  type : createjs.LoadQueue.IMAGE, id : "ventilador"},
      {src : "assets/word/chapeu.png",      type : createjs.LoadQueue.IMAGE, id : "chapeu"},
      {src : "assets/word/lixeira.png",     type : createjs.LoadQueue.IMAGE, id : "lixeira"},
      {src : "assets/word/porco.png",       type : createjs.LoadQueue.IMAGE, id : "porco"},
      // level 6
      {src : "assets/word/joaninha.png",     type : createjs.LoadQueue.IMAGE, id : "joaninha"},
      {src : "assets/word/estrela.png",     type : createjs.LoadQueue.IMAGE, id : "estrela"},
      {src : "assets/word/martelo.png",     type : createjs.LoadQueue.IMAGE, id : "martelo"},
      {src : "assets/word/pena.png",        type : createjs.LoadQueue.IMAGE, id : "pena"},
      {src : "assets/word/peixe.png",       type : createjs.LoadQueue.IMAGE, id : "peixe"},
      {src : "assets/word/foguete.png",     type : createjs.LoadQueue.IMAGE, id : "foguete"},
      {src : "assets/word/piano.png",       type : createjs.LoadQueue.IMAGE, id : "piano"},
      {src : "assets/word/controle.png",    type : createjs.LoadQueue.IMAGE, id : "controle"},
      {src : "assets/word/cofre.png",       type : createjs.LoadQueue.IMAGE, id : "cofre"},
      {src : "assets/word/coco.png",        type : createjs.LoadQueue.IMAGE, id : "coco"},
      // level 7
      {src : "assets/word/calculadora.png", type : createjs.LoadQueue.IMAGE, id : "calculadora"},
      {src : "assets/word/cogumelo.png",    type : createjs.LoadQueue.IMAGE, id : "cogumelo"},
      {src : "assets/word/computador.png",  type : createjs.LoadQueue.IMAGE, id : "computador"},
      {src : "assets/word/muro.png",        type : createjs.LoadQueue.IMAGE, id : "muro"},
      {src : "assets/word/roda.png",        type : createjs.LoadQueue.IMAGE, id : "roda"},
      {src : "assets/word/disco.png",       type : createjs.LoadQueue.IMAGE, id : "disco"},
      {src : "assets/word/alho.png",        type : createjs.LoadQueue.IMAGE, id : "alho"},
      {src : "assets/word/lupa.png",        type : createjs.LoadQueue.IMAGE, id : "lupa"},
      {src : "assets/word/bateria.png",     type : createjs.LoadQueue.IMAGE, id : "bateria"},
      {src : "assets/word/cama.png",        type : createjs.LoadQueue.IMAGE, id : "cama"},
      {src : "assets/word/caixa.png",       type : createjs.LoadQueue.IMAGE, id : "caixa"},
      {src : "assets/word/livros.png",      type : createjs.LoadQueue.IMAGE, id : "livros"},
      // AUDIO
      {src : "assets/audio/fase1.mp3",          type : createjs.LoadQueue.SOUND, id : "fase1"},
      {src : "assets/audio/fase2.mp3",          type : createjs.LoadQueue.SOUND, id : "fase2"},
      {src : "assets/audio/fase3.mp3",          type : createjs.LoadQueue.SOUND, id : "fase3"},
      {src : "assets/audio/fase4.mp3",          type : createjs.LoadQueue.SOUND, id : "fase4"},
      {src : "assets/audio/fase5.mp3",          type : createjs.LoadQueue.SOUND, id : "fase5"},
      {src : "assets/audio/fase6.mp3",          type : createjs.LoadQueue.SOUND, id : "fase6"},
      {src : "assets/audio/fase7.mp3",          type : createjs.LoadQueue.SOUND, id : "fase7"},
      {src : "assets/audio/ajuda.mp3",          type : createjs.LoadQueue.SOUND, id : "ajuda"},
      {src : "assets/audio/creditos.mp3",       type : createjs.LoadQueue.SOUND, id : "creditos"},
      {src : "assets/audio/finalizacao.mp3",    type : createjs.LoadQueue.SOUND, id : "finalizacao"},
      {src : "assets/audio/gameoverletras.mp3", type : createjs.LoadQueue.SOUND, id : "gameoverletras"},
      {src : "assets/audio/gameovertempo.mp3",  type : createjs.LoadQueue.SOUND, id : "gameovertempo"},
      {src : "assets/audio/informacoes.mp3",    type : createjs.LoadQueue.SOUND, id : "informacoes"},
      {src : "assets/audio/instrucoes.mp3",     type : createjs.LoadQueue.SOUND, id : "instrucoes"},
      {src : "assets/audio/opcoes.mp3",         type : createjs.LoadQueue.SOUND, id : "opcoes"},
      {src : "assets/audio/ranking.mp3",        type : createjs.LoadQueue.SOUND, id : "ranking"},
      {src : "assets/audio/sucesso.mp3",        type : createjs.LoadQueue.SOUND, id : "sucesso"},
      {src : "assets/audio/titulo.mp3",         type : createjs.LoadQueue.SOUND, id : "titulosound"},
      {src : "assets/audio/marimbamelody.mp3",  type : createjs.LoadQueue.SOUND, id : "musica"},
      {src : "assets/audio/popphoenix.mp3",     type : createjs.LoadQueue.SOUND, id : "pop"},
      {src : "assets/audio/right.mp3",          type : createjs.LoadQueue.SOUND, id : "right"},
      {src : "assets/audio/wrong.mp3",          type : createjs.LoadQueue.SOUND, id : "wrong"}
];